version: "3"
services:
  nginx:
    image: nginx:1
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - "redmine"

  postgre:
    image: postgres:10.6-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=a
      - POSTGRES_USER=redmine
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redmine:
    image: redmine:3.4
    restart: always
    environment:
      - REDMINE_DB_POSTGRES=postgre
      - REDMINE_DB_USERNAME=redmine
      - REDMINE_DB_PASSWORD=a
    volumes:
      - ./plugins:/usr/src/redmine/plugins
      - ./themes:/usr/src/redmine/public/themes
    depends_on:
      - "postgre"
